apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::311141540332:role/dev-eks-node-role
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

    - rolearn: arn:aws:iam::311141540332:role/userRole
      username: github-actions
      groups:
        - system:masters

   # mapRoles: |
   # - rolearn: arn:aws:iam::311141540332:role/EKSDevRole
   # username: eks-dev
    #groups:
    #  - dev-group

