apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fullproject-app
  namespace: argocd
spec:
  project: default

  # The source of your manifests (Git repo)
  source:
    repoURL: 'https://github.com/dennis8050/fullproject.git'  # your repo
    targetRevision: dev  # branch
    path: k8s/dev      # path in repo where manifests are

  # Destination cluster and namespace
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev

  # Sync policy (automatic sync optional)
  syncPolicy:
    automated:
      prune: true          # delete resources removed from Git
      selfHeal: true       # fix drift automatically
    syncOptions:
      - CreateNamespace=true  # create namespace if missing
